name: .NET Build & Publish

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2022]
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: src

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build --verbosity normal --configuration Release

      - name: Pack NuGet package
        if: matrix.os == 'ubuntu-latest'
        run: dotnet pack --configuration Release -o ../artifacts

      - name: Add GitHub NuGet source
        if: matrix.os == 'ubuntu-latest'
        run: dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --name github --username ${{ github.actor }} --password ${{ secrets.APIBLUEPRINT_TOKEN }} --store-password-in-clear-text

      - name: Publish to GitHub Packages
        if: matrix.os == 'ubuntu-latest'
        run: dotnet nuget push "./artifacts/*.nupkg" --source github --api-key ${{ secrets.APIBLUEPRINT_TOKEN }}
